spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d072bfeab6c57fe45a02
            clientSecret: 78cd8438fca68cffeb512faf1e3fc7e2115b4575
  application:
    name: spring-cloud-eureka-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true