spring:
  application:
    name: spring-ftp
server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
ftp:
  host: localhost
  port: 21
  username: anonymous
  password:
  channel: default